name: uied-env
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.7
    - opencv=3.4.2
    - numpy
    - pandas
    - tqdm
    - scikit-learn=0.22.2
    - pip
    - pip:
          - keras==2.2.4
          - paddleocr
          - paddlepaddle
          - tensorflow==1.14.0
